### ISSUE TITLE
webpack compiles with errors

### ISSUE THREAD

**Issue by isaac-svg** [abhay-raj19/FitBody#5]
Module not found: Error: can't resolve `emixicon.ttf?t=1590207869815 in node_modules 
![image](https://github.com/abhay-raj19/FitBody/assets/109481712/2b51eb45-3510-42ef-a89d-87db6a54098c)

**Comment by isaac-svg** [comment]
This is the the compile error when you run the application `npm run start`

**Comment by abhay-raj19** [comment]
while i am running the same application by cloning it up is not raising up a single error and is totally compiles up .

<img width="1920" alt="image" src="https://github.com/abhay-raj19/FitBody/assets/96302417/52df815c-b9e3-4657-af2c-aa268593cf34">


i think the issue is with your file system and 

Steps:
git clone <address >
npm start

**Comment by abhay-raj19** [comment]
my all things are working up fine ...

Look at this :
<img width="965" alt="image" src="https://github.com/abhay-raj19/FitBody/assets/96302417/d99cd49c-0d15-4e1b-bf1a-4910dbddf24d">

**Comment by abhay-raj19** [comment]
are you debbuging up the errors that you get while running `npm run start` or you are not able to run the application locally?

**Comment by isaac-svg** [comment]
I have figured it out thanks
